/* ui_html.h — Auto-generated from ui.html. Do not edit. */
#ifndef HUGO_UI_HTML_H
#define HUGO_UI_HTML_H

static const char UI_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"vi\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<title>HUGO DB</title>\n"
    "<link href=\"https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500;600&family=Source+Sans+3:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\n"
    "<style>\n"
    "  :root {\n"
    "    --bg: #FFFFFF;\n"
    "    --bg-sec: #F9FBFA;\n"
    "    --bg-side: #F9FBFA;\n"
    "    --bg-hover: #E8EDEB;\n"
    "    --bg-doc: #FFFFFF;\n"
    "    --border: #E8EDEB;\n"
    "    --border-strong: #C1C7C6;\n"
    "    --text: #1C2D38;\n"
    "    --text-sec: #5C6C75;\n"
    "    --text-muted: #889397;\n"
    "    --green: #00ED64;\n"
    "    --green-dark: #00A35C;\n"
    "    --green-darker: #00684A;\n"
    "    --green-bg: #E3FCF7;\n"
    "    --green-border: #71F6BA;\n"
    "    --blue: #016BF8;\n"
    "    --blue-light: #E1F7FF;\n"
    "    --yellow: #FFC010;\n"
    "    --yellow-bg: #FFF1CF;\n"
    "    --red: #DB3030;\n"
    "    --red-bg: #FFEFEF;\n"
    "    --mono: 'Source Code Pro', Consolas, 'Courier New', monospace;\n"
    "    --sans: 'Source Sans 3', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n"
    "    --shadow-sm: 0 1px 2px rgba(0,0,0,0.06);\n"
    "    --shadow-md: 0 2px 8px rgba(0,0,0,0.08);\n"
    "    --radius: 6px;\n"
    "  }\n"
    "  * { box-sizing: border-box; }\n"
    "  body {\n"
    "    margin: 0; font-family: var(--sans); background: var(--bg); color: var(--text);\n"
    "    height: 100vh; display: flex; flex-direction: column; font-size: 14px; line-height: 1.5;\n"
    "  }\n"
    "\n"
    "  /* ===== Top header bar ===== */\n"
    "  .topbar {\n"
    "    background: #1C2D38; color: #fff; display: flex; align-items: center;\n"
    "    padding: 0 16px; height: 40px; flex-shrink: 0; font-size: 13px; gap: 12px;\n"
    "  }\n"
    "  .topbar .logo {\n"
    "    font-weight: 700; font-size: 14px; letter-spacing: 0.5px; display: flex; align-items: center; gap: 6px;\n"
    "  }\n"
    "  .topbar .logo .leaf { color: var(--green); font-size: 18px; }\n"
    "  .topbar .connection {\n"
    "    background: rgba(255,255,255,0.1); border-radius: 4px; padding: 3px 10px;\n"
    "    font-family: var(--mono); font-size: 12px; color: #C1C7C6;\n"
    "  }\n"
    "  .topbar .spacer { flex: 1; }\n"
    "  .topbar .status { display: flex; align-items: center; gap: 5px; font-size: 12px; color: #C1C7C6; }\n"
    "  .topbar .dot { width: 8px; height: 8px; border-radius: 50%; }\n"
    "  .topbar .dot.ok { background: var(--green); }\n"
    "  .topbar .dot.err { background: var(--red); }\n"
    "\n"
    "  /* ===== Breadcrumb + tabs ===== */\n"
    "  .nav-bar {\n"
    "    background: var(--bg); border-bottom: 1px solid var(--border);\n"
    "    padding: 0 20px; display: flex; flex-direction: column;\n"
    "  }\n"
    "  .breadcrumb {\n"
    "    font-size: 13px; padding: 10px 0 0; display: flex; align-items: center; gap: 4px;\n"
    "    color: var(--text-sec);\n"
    "  }\n"
    "  .breadcrumb a {\n"
    "    color: var(--blue); text-decoration: none; cursor: pointer;\n"
    "  }\n"
    "  .breadcrumb a:hover { text-decoration: underline; }\n"
    "  .breadcrumb .sep { color: var(--text-muted); margin: 0 2px; }\n"
    "  .breadcrumb .current { color: var(--text); font-weight: 600; }\n"
    "  .tab-bar {\n"
    "    display: flex; gap: 0; margin-top: 6px;\n"
    "  }\n"
    "  .tab-item {\n"
    "    padding: 8px 16px; font-size: 13px; color: var(--text-sec);\n"
    "    cursor: pointer; border-bottom: 3px solid transparent;\n"
    "    font-weight: 500; user-select: none; position: relative;\n"
    "  }\n"
    "  .tab-item:hover { color: var(--text); }\n"
    "  .tab-item.active {\n"
    "    color: var(--text); font-weight: 600; border-bottom-color: var(--green-darker);\n"
    "  }\n"
    "  .tab-item .badge {\n"
    "    font-size: 11px; background: var(--bg-sec); border: 1px solid var(--border);\n"
    "    border-radius: 10px; padding: 0 6px; margin-left: 4px; color: var(--text-sec);\n"
    "    font-weight: 500;\n"
    "  }\n"
    "  .tab-item.active .badge { background: var(--green-bg); border-color: var(--green-border); color: var(--green-darker); }\n"
    "\n"
    "  /* ===== Main layout ===== */\n"
    "  main { flex: 1; display: flex; overflow: hidden; }\n"
    "\n"
    "  /* ===== Sidebar ===== */\n"
    "  #sidebar {\n"
    "    width: 260px; background: var(--bg-side); border-right: 1px solid var(--border);\n"
    "    display: flex; flex-direction: column; overflow: hidden; font-size: 13px;\n"
    "  }\n"
    "  .side-hdr {\n"
    "    padding: 12px 12px 8px; display: flex; align-items: center; justify-content: space-between;\n"
    "    border-bottom: 1px solid var(--border);\n"
    "  }\n"
    "  .side-hdr span { font-weight: 600; font-size: 12px; text-transform: uppercase; color: var(--text-sec); letter-spacing: 0.3px; }\n"
    "  .side-hdr .btns { display: flex; gap: 4px; }\n"
    "  .side-hdr .btns button {\n"
    "    background: none; border: none; color: var(--text-muted); cursor: pointer;\n"
    "    font-size: 14px; padding: 2px 4px; border-radius: 3px;\n"
    "  }\n"
    "  .side-hdr .btns button:hover { background: var(--bg-hover); color: var(--text); }\n"
    "  #coll-list { flex: 1; overflow-y: auto; padding: 4px 0; }\n"
    "  .coll-item {\n"
    "    padding: 6px 12px 6px 16px; cursor: pointer; display: flex; align-items: center;\n"
    "    gap: 6px; color: var(--text-sec); transition: background 0.1s;\n"
    "  }\n"
    "  .coll-item:hover { background: var(--bg-hover); color: var(--text); }\n"
    "  .coll-item.active { background: var(--green-bg); color: var(--green-darker); font-weight: 600; }\n"
    "  .coll-item .icon { font-size: 12px; color: var(--text-muted); flex-shrink: 0; }\n"
    "  .coll-item.active .icon { color: var(--green-darker); }\n"
    "  .coll-item .name { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }\n"
    "  .coll-item .cnt {\n"
    "    font-size: 11px; color: var(--text-muted); font-family: var(--mono);\n"
    "  }\n"
    "  .coll-item.active .cnt { color: var(--green-darker); }\n"
    "  .coll-item .dots {\n"
    "    opacity: 0; font-size: 12px; color: var(--text-muted); cursor: pointer; padding: 2px;\n"
    "  }\n"
    "  .coll-item:hover .dots { opacity: 1; }\n"
    "  .side-empty { padding: 20px 16px; color: var(--text-muted); font-size: 12px; text-align: center; }\n"
    "  .side-tree-parent {\n"
    "    padding: 6px 12px; display: flex; align-items: center; gap: 6px;\n"
    "    color: var(--text); font-weight: 600; font-size: 13px; cursor: pointer;\n"
    "  }\n"
    "  .side-tree-parent .arrow { font-size: 10px; color: var(--text-muted); }\n"
    "\n"
    "  /* ===== Content area ===== */\n"
    "  #content-area { flex: 1; display: flex; flex-direction: column; overflow: hidden; }\n"
    "  #content { flex: 1; overflow: auto; padding: 16px 20px; background: var(--bg-sec); }\n"
    "  .pane { display: none; }\n"
    "  .pane.active { display: block; }\n"
    "\n"
    "  /* ===== Query filter bar (like Compass) ===== */\n"
    "  .filter-bar {\n"
    "    background: var(--bg); border: 1px solid var(--border); border-radius: var(--radius);\n"
    "    padding: 10px 14px; display: flex; align-items: center; gap: 10px;\n"
    "    box-shadow: var(--shadow-sm); margin-bottom: 12px;\n"
    "  }\n"
    "  .filter-bar .filter-icon { color: var(--green-darker); font-size: 14px; }\n"
    "  .filter-bar input {\n"
    "    flex: 1; border: none; background: none; font-family: var(--mono);\n"
    "    font-size: 13px; color: var(--text); outline: none;\n"
    "  }\n"
    "  .filter-bar input::placeholder { color: var(--text-muted); }\n"
    "  .btn {\n"
    "    display: inline-flex; align-items: center; gap: 4px; padding: 6px 14px;\n"
    "    border-radius: 4px; font-size: 13px; font-weight: 600; cursor: pointer;\n"
    "    font-family: var(--sans); border: 1px solid transparent; transition: all 0.1s;\n"
    "  }\n"
    "  .btn-green { background: var(--green-darker); color: #fff; border-color: var(--green-darker); }\n"
    "  .btn-green:hover { background: #005C3E; }\n"
    "  .btn-outline {\n"
    "    background: var(--bg); color: var(--text); border: 1px solid var(--border-strong);\n"
    "  }\n"
    "  .btn-outline:hover { background: var(--bg-hover); }\n"
    "  .btn-red { background: var(--bg); color: var(--red); border: 1px solid var(--red); }\n"
    "  .btn-red:hover { background: var(--red-bg); }\n"
    "  .btn-sm { padding: 4px 10px; font-size: 12px; font-weight: 500; }\n"
    "  .btn-blue { background: var(--blue); color: #fff; border-color: var(--blue); }\n"
    "  .btn-blue:hover { background: #0050C8; }\n"
    "\n"
    "  /* ===== Toolbar (like Compass ADD DATA / UPDATE / DELETE row) ===== */\n"
    "  .toolbar {\n"
    "    display: flex; align-items: center; gap: 8px; margin-bottom: 12px; flex-wrap: wrap;\n"
    "  }\n"
    "  .toolbar .sep { width: 1px; height: 20px; background: var(--border); margin: 0 4px; }\n"
    "  .toolbar .spacer { flex: 1; }\n"
    "  .toolbar .page-info {\n"
    "    font-size: 12px; color: var(--text-sec); font-family: var(--mono);\n"
    "    display: flex; align-items: center; gap: 6px;\n"
    "  }\n"
    "  .toolbar .page-info select {\n"
    "    border: 1px solid var(--border-strong); border-radius: 4px; padding: 3px 6px;\n"
    "    font-size: 12px; font-family: var(--mono); background: var(--bg); color: var(--text);\n"
    "  }\n"
    "  .toolbar .page-nav {\n"
    "    display: flex; gap: 2px;\n"
    "  }\n"
    "  .toolbar .page-nav button {\n"
    "    background: var(--bg); border: 1px solid var(--border); color: var(--text-sec);\n"
    "    width: 28px; height: 28px; border-radius: 4px; cursor: pointer;\n"
    "    display: flex; align-items: center; justify-content: center; font-size: 12px;\n"
    "  }\n"
    "  .toolbar .page-nav button:hover:not(:disabled) { background: var(--bg-hover); color: var(--text); }\n"
    "  .toolbar .page-nav button:disabled { opacity: 0.4; cursor: default; }\n"
    "  .toolbar .refresh-btn {\n"
    "    background: none; border: none; color: var(--text-muted); cursor: pointer;\n"
    "    font-size: 14px; padding: 4px;\n"
    "  }\n"
    "  .toolbar .refresh-btn:hover { color: var(--text); }\n"
    "  .toolbar .view-toggle {\n"
    "    display: flex; border: 1px solid var(--border); border-radius: 4px; overflow: hidden;\n"
    "  }\n"
    "  .toolbar .view-toggle button {\n"
    "    background: var(--bg); border: none; color: var(--text-muted); padding: 4px 8px;\n"
    "    cursor: pointer; font-size: 13px; border-right: 1px solid var(--border);\n"
    "  }\n"
    "  .toolbar .view-toggle button:last-child { border-right: none; }\n"
    "  .toolbar .view-toggle button.active { background: var(--bg-hover); color: var(--text); }\n"
    "  .toolbar .view-toggle button:hover { background: var(--bg-hover); }\n"
    "\n"
    "  /* ===== Document cards (list view like Compass) ===== */\n"
    "  .doc-card {\n"
    "    background: var(--bg-doc); border: 1px solid var(--border); border-radius: var(--radius);\n"
    "    padding: 14px 18px; margin-bottom: 8px; font-family: var(--mono); font-size: 13px;\n"
    "    line-height: 1.6; box-shadow: var(--shadow-sm); transition: border-color 0.15s;\n"
    "  }\n"
    "  .doc-card:hover { border-color: var(--border-strong); }\n"
    "  .doc-field { display: flex; gap: 8px; padding: 1px 0; }\n"
    "  .doc-key { color: var(--text-sec); min-width: 120px; flex-shrink: 0; }\n"
    "  .doc-key::after { content: \" :\"; }\n"
    "  .doc-val-str { color: var(--green-darker); }\n"
    "  .doc-val-str::before, .doc-val-str::after { content: '\"'; color: var(--text-muted); }\n"
    "  .doc-val-num { color: var(--text); }\n"
    "  .doc-val-bool { color: var(--yellow); font-weight: 600; }\n"
    "  .doc-val-null { color: var(--text-muted); font-style: italic; }\n"
    "  .doc-val-date { color: var(--blue); }\n"
    "  .doc-val-id { color: var(--text-sec); }\n"
    "  .doc-val-obj { color: var(--text-muted); }\n"
    "  .doc-val-obj::before { content: \"\xe2\x96\xb8 \"; font-size: 10px; }\n"
    "\n"
    "  /* ===== Table view ===== */\n"
    "  .table-scroll-container {\n"
    "    overflow-x: auto; overflow-y: auto;\n"
    "    border: 1px solid var(--border); border-radius: var(--radius);\n"
    "    background: var(--bg-doc);\n"
    "    max-height: calc(100vh - 320px);  /* fixed height: scroll ch\xe1\xbb\x89 trong container */\n"
    "  }\n"
    "  .table-scroll-container table {\n"
    "    width: max-content; min-width: 100%; border-collapse: collapse; font-size: 13px;\n"
    "    background: var(--bg-doc); border: none; border-radius: 0;\n"
    "    table-layout: auto;  /* columns auto-size to widest content */\n"
    "  }\n"
    "  table {\n"
    "    width: 100%; border-collapse: collapse; font-size: 13px; background: var(--bg-doc);\n"
    "    border: 1px solid var(--border); border-radius: var(--radius); overflow: hidden;\n"
    "  }\n"
    "  th, td {\n"
    "    padding: 8px 14px; text-align: left; border-bottom: 1px solid var(--border);\n"
    "    white-space: nowrap; max-width: none;  /* m\xe1\xbb\x8di cell 1 d\xc3\xb2ng, kh\xc3\xb4ng xu\xe1\xbb\x91ng d\xc3\xb2ng */\n"
    "    overflow: hidden; text-overflow: ellipsis;\n"
    "  }\n"
    "  /* Trong scroll container: columns size to content, kh\xc3\xb4ng ellipsis */\n"
    "  .table-scroll-container th,\n"
    "  .table-scroll-container td {\n"
    "    overflow: visible; text-overflow: unset;\n"
    "  }\n"
    "  th {\n"
    "    background: var(--bg-sec); color: var(--text-sec); font-weight: 600; font-size: 12px;\n"
    "    position: sticky; top: 0; z-index: 1; cursor: pointer; user-select: none;\n"
    "  }\n"
    "  th:hover { background: var(--bg-hover); color: var(--text); }\n"
    "  th .sort-arrow { color: var(--text-muted); margin-left: 4px; font-size: 10px; }\n"
    "  tr:last-child td { border-bottom: none; }\n"
    "  tr:hover td { background: #F3FBF9; }\n"
    "  td.num { text-align: right; font-family: var(--mono); }\n"
    "  td.str { color: var(--green-darker); font-family: var(--mono); }\n"
    "  td.bool { color: #B45309; font-family: var(--mono); }\n"
    "  td.null { color: var(--text-muted); font-style: italic; }\n"
    "  td.id-col { color: var(--text-sec); font-family: var(--mono); }\n"
    "\n"
    "  /* ===== Query editor ===== */\n"
    "  textarea.code {\n"
    "    width: 100%; font-family: var(--mono); font-size: 13px; padding: 12px 14px;\n"
    "    background: var(--bg-doc); color: var(--text); border: 1px solid var(--border);\n"
    "    border-radius: var(--radius); resize: vertical; line-height: 1.5;\n"
    "    box-shadow: var(--shadow-sm);\n"
    "  }\n"
    "  textarea.code:focus { outline: none; border-color: var(--blue); box-shadow: 0 0 0 3px rgba(1,107,248,0.12); }\n"
    "\n"
    "  /* ===== Result banner ===== */\n"
    "  .result-banner {\n"
    "    padding: 8px 14px; border-radius: var(--radius); font-size: 13px;\n"
    "    margin-bottom: 12px; display: flex; align-items: center; gap: 6px;\n"
    "  }\n"
    "  .result-banner.ok { background: var(--green-bg); border: 1px solid var(--green-border); color: var(--green-darker); }\n"
    "  .result-banner.err { background: var(--red-bg); border: 1px solid #F5C6C6; color: var(--red); }\n"
    "  .result-banner.info { background: var(--blue-light); border: 1px solid #B8E3FF; color: var(--blue); }\n"
    "\n"
    "  /* ===== Import dropzone ===== */\n"
    "  .dropzone {\n"
    "    border: 2px dashed var(--border-strong); border-radius: 8px; padding: 48px 24px;\n"
    "    text-align: center; color: var(--text-sec); transition: all 0.15s; background: var(--bg-doc);\n"
    "  }\n"
    "  .dropzone.drag { border-color: var(--green); background: var(--green-bg); color: var(--green-darker); }\n"
    "  .dropzone p { margin: 6px 0; }\n"
    "  .form-row { display: flex; gap: 10px; margin-bottom: 14px; align-items: center; }\n"
    "  .form-row label { min-width: 140px; color: var(--text-sec); font-size: 13px; font-weight: 500; }\n"
    "  input.field {\n"
    "    background: var(--bg-doc); color: var(--text); border: 1px solid var(--border-strong);\n"
    "    padding: 7px 10px; border-radius: 4px; font-family: var(--mono); font-size: 13px; flex: 1;\n"
    "  }\n"
    "  input.field:focus { outline: none; border-color: var(--blue); box-shadow: 0 0 0 3px rgba(1,107,248,0.12); }\n"
    "\n"
    "  /* ===== Batch stats ===== */\n"
    "  .batch-stats {\n"
    "    display: grid; grid-template-columns: repeat(auto-fit, minmax(110px, 1fr));\n"
    "    gap: 8px; margin-bottom: 14px;\n"
    "  }\n"
    "  .batch-stat {\n"
    "    background: var(--bg-doc); border: 1px solid var(--border); border-radius: var(--radius);\n"
    "    padding: 10px 12px;\n"
    "  }\n"
    "  .batch-stat .k { font-size: 10px; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.3px; }\n"
    "  .batch-stat .v { font-family: var(--mono); font-size: 15px; color: var(--green-darker); margin-top: 2px; font-weight: 600; }\n"
    "\n"
    "  /* ===== Stats cards ===== */\n"
    "  .stats-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 12px; margin-bottom: 20px; }\n"
    "  .stat-card {\n"
    "    background: var(--bg-doc); border: 1px solid var(--border); border-radius: var(--radius);\n"
    "    padding: 16px; box-shadow: var(--shadow-sm);\n"
    "  }\n"
    "  .stat-card .label { font-size: 11px; text-transform: uppercase; color: var(--text-muted); letter-spacing: 0.4px; font-weight: 600; }\n"
    "  .stat-card .value { font-size: 28px; font-weight: 700; margin-top: 6px; color: var(--green-darker); font-family: var(--mono); }\n"
    "  .stat-card .sub { font-size: 11px; color: var(--text-muted); margin-top: 4px; }\n"
    "  .section-title { font-size: 12px; text-transform: uppercase; color: var(--text-muted); letter-spacing: 0.5px; margin: 20px 0 8px; font-weight: 600; }\n"
    "\n"
    "  .empty { text-align: center; color: var(--text-muted); padding: 48px 24px; font-size: 14px; }\n"
    "  .hint { color: var(--text-muted); font-size: 11px; font-family: var(--mono); }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "  <!-- Top bar -->\n"
    "  <div class=\"topbar\">\n"
    "    <div class=\"logo\"><span class=\"leaf\">\xf0\x9f\x8d\x83</span> HUGO DB</div>\n"
    "    <div class=\"connection\" id=\"db-badge\">localhost</div>\n"
    "    <div class=\"spacer\"></div>\n"
    "    <div class=\"status\"><div class=\"dot\" id=\"status-dot\"></div><span id=\"status-text\">connecting...</span></div>\n"
    "  </div>\n"
    "\n"
    "  <main>\n"
    "    <!-- Sidebar -->\n"
    "    <aside id=\"sidebar\">\n"
    "      <div class=\"side-hdr\">\n"
    "        <span>Connections (1)</span>\n"
    "        <div class=\"btns\">\n"
    "          <button onclick=\"refreshAll()\" title=\"Refresh\">\xe2\x86\xbb</button>\n"
    "          <button onclick=\"switchTab('import')\" title=\"Add\">+</button>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"sidebar-tree\"></div>\n"
    "    </aside>\n"
    "\n"
    "    <!-- Content -->\n"
    "    <section id=\"content-area\">\n"
    "      <!-- Nav bar -->\n"
    "      <div class=\"nav-bar\">\n"
    "        <div class=\"breadcrumb\" id=\"breadcrumb\"></div>\n"
    "        <div class=\"tab-bar\" id=\"tab-bar\"></div>\n"
    "      </div>\n"
    "\n"
    "      <div id=\"content\">\n"
    "        <!-- Overview -->\n"
    "        <div class=\"pane active\" data-pane=\"overview\">\n"
    "          <div class=\"stats-grid\" id=\"overview-stats\"></div>\n"
    "          <div class=\"section-title\">Collections</div>\n"
    "          <div id=\"overview-colls\"></div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Documents -->\n"
    "        <div class=\"pane\" data-pane=\"docs\">\n"
    "          <div id=\"docs-empty\" class=\"empty\">Select a collection from the sidebar to view documents</div>\n"
    "          <div id=\"docs-view\" style=\"display:none\">\n"
    "            <div class=\"filter-bar\">\n"
    "              <span class=\"filter-icon\">\xe2\x8a\x95</span>\n"
    "              <input type=\"text\" id=\"docs-filter\" placeholder=\"Type a query: { field: 'value' } or Generate query \xe2\x9c\xa6\" onkeydown=\"if(event.key==='Enter')docsApplyFilter()\">\n"
    "              <button class=\"btn btn-outline btn-sm\" onclick=\"docsApplyFilter()\">Find</button>\n"
    "              <button class=\"btn btn-outline btn-sm\" onclick=\"$('docs-filter').value=''; docsReload()\">Reset</button>\n"
    "            </div>\n"
    "            <div class=\"toolbar\">\n"
    "              <button class=\"btn btn-green btn-sm\" onclick=\"switchTab('import')\">\xe2\x8a\x95 ADD DATA \xe2\x96\xbe</button>\n"
    "              <div class=\"sep\"></div>\n"
    "              <button class=\"btn btn-outline btn-sm\" onclick=\"switchTab('query')\">\xe2\x8a\x95 QUERY</button>\n"
    "              <div class=\"spacer\"></div>\n"
    "              <div class=\"page-info\">\n"
    "                <select id=\"docs-per-page\" onchange=\"docsReload()\">\n"
    "                  <option>25</option><option selected>50</option><option>100</option><option>200</option>\n"
    "                </select>\n"
    "                <span id=\"docs-page-info\">\xe2\x80\x94</span>\n"
    "                <button class=\"refresh-btn\" onclick=\"docsReload()\">\xe2\x86\xbb</button>\n"
    "              </div>\n"
    "              <div class=\"page-nav\">\n"
    "                <button onclick=\"docsPage(-1)\" id=\"docs-prev\" title=\"Previous page\">\xe2\x80\xb9</button>\n"
    "                <button onclick=\"docsPage(1)\" id=\"docs-next\" title=\"Next page\">\xe2\x80\xba</button>\n"
    "              </div>\n"
    "              <div class=\"view-toggle\">\n"
    "                <button id=\"view-list\" class=\"active\" onclick=\"setViewMode('list')\" title=\"List view\">\xe2\x98\xb0</button>\n"
    "                <button id=\"view-table\" onclick=\"setViewMode('table')\" title=\"Table view\">\xe2\x8a\x9e</button>\n"
    "              </div>\n"
    "            </div>\n"
    "            <div id=\"docs-table\"></div>\n"
    "            <div style=\"padding:8px 0;font-size:12px;color:var(--text-muted);font-family:var(--mono)\" id=\"docs-count-info\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Query -->\n"
    "        <div class=\"pane\" data-pane=\"query\">\n"
    "          <div style=\"margin-bottom:10px\">\n"
    "            <textarea id=\"query\" class=\"code\" rows=\"5\" placeholder=\"HugoQL query, e.g. funden users haar age $bh 20 orange bi age desc lime 10\"></textarea>\n"
    "          </div>\n"
    "          <div class=\"toolbar\">\n"
    "            <button class=\"btn btn-green\" onclick=\"runQuery()\">Find</button>\n"
    "            <button class=\"btn btn-outline\" onclick=\"$('query').value='';$('query-result').innerHTML=''\">Reset</button>\n"
    "            <span class=\"hint\" style=\"margin-left:4px\">Ctrl+Enter</span>\n"
    "            <div class=\"spacer\"></div>\n"
    "            <span style=\"font-size:12px;color:var(--text-muted)\">Samples:</span>\n"
    "            <button class=\"btn btn-outline btn-sm\" onclick=\"setQuery('madeco users')\">madeco</button>\n"
    "            <button class=\"btn btn-outline btn-sm\" onclick='setQuery(\"vietinfo users { name: \\\"Alice\\\", age: 20 }\")'>vietinfo</button>\n"
    "            <button class=\"btn btn-outline btn-sm\" onclick=\"setQuery('funden users haar age $bh 18 orange bi age desc lime 5')\">complex</button>\n"
    "            <button class=\"btn btn-outline btn-sm\" onclick=\"setQuery('skill')\">skill</button>\n"
    "            <div class=\"view-toggle\" style=\"margin-left:8px\">\n"
    "              <button id=\"qview-list\" class=\"active\" onclick=\"setQueryViewMode('list')\" title=\"List view\">\xe2\x98\xb0</button>\n"
    "              <button id=\"qview-table\" onclick=\"setQueryViewMode('table')\" title=\"Table view\">\xe2\x8a\x9e</button>\n"
    "            </div>\n"
    "          </div>\n"
    "          <div id=\"query-result\" style=\"margin-top:16px\"></div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Batch -->\n"
    "        <div class=\"pane\" data-pane=\"batch\">\n"
    "          <div style=\"margin-bottom:10px\">\n"
    "            <textarea id=\"batch-text\" class=\"code\" rows=\"10\" placeholder=\"Multiple queries, 1 per line. Comments: -- or #\"></textarea>\n"
    "          </div>\n"
    "          <div class=\"toolbar\">\n"
    "            <button class=\"btn btn-green\" onclick=\"runBatch()\">Run Batch</button>\n"
    "            <span class=\"hint\">Each line = 1 query. p50/p95/p99 reported.</span>\n"
    "            <div class=\"spacer\"></div>\n"
    "            <button class=\"btn btn-outline btn-sm\" onclick=\"loadBatchSample()\">Load sample</button>\n"
    "          </div>\n"
    "          <div id=\"batch-result\" style=\"margin-top:16px\"></div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Import -->\n"
    "        <div class=\"pane\" data-pane=\"import\">\n"
    "          <div class=\"form-row\">\n"
    "            <label>Target collection:</label>\n"
    "            <input class=\"field\" type=\"text\" id=\"import-coll\" placeholder=\"e.g. users (will be created if new)\">\n"
    "          </div>\n"
    "          <div id=\"dropzone\" class=\"dropzone\"\n"
    "               ondragover=\"event.preventDefault();this.classList.add('drag')\"\n"
    "               ondragleave=\"this.classList.remove('drag')\"\n"
    "               ondrop=\"handleDrop(event)\">\n"
    "            <p style=\"font-size:28px;margin:0\">\xf0\x9f\x93\x84</p>\n"
    "            <p><strong>Drop a JSONL file here</strong></p>\n"
    "            <p style=\"font-size:12px;color:var(--text-muted)\">or <label style=\"color:var(--blue);cursor:pointer;text-decoration:underline\">browse<input type=\"file\" id=\"import-file\" style=\"display:none\" onchange=\"handleFileInput(event)\"></label></p>\n"
    "            <p style=\"font-size:11px;color:var(--text-muted)\">Format: 1 JSON object per line. Max 16MB.</p>\n"
    "          </div>\n"
    "          <details style=\"margin-top:14px\">\n"
    "            <summary style=\"cursor:pointer;color:var(--text-muted);font-size:12px;font-weight:500\">\xe2\x96\xb8 Paste JSONL directly</summary>\n"
    "            <textarea id=\"import-text\" class=\"code\" rows=\"6\" style=\"margin-top:8px\" placeholder='{\"name\":\"Alice\",\"age\":20}&#10;{\"name\":\"Bob\",\"age\":22}'></textarea>\n"
    "            <button class=\"btn btn-outline\" style=\"margin-top:8px\" onclick=\"importPasted()\">Import pasted</button>\n"
    "          </details>\n"
    "          <div id=\"import-result\" style=\"margin-top:16px\"></div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </section>\n"
    "  </main>\n"
    "\n"
    "<script>\n"
    "let S = {\n"
    "  currentColl: null, docsPage: 0, docsPerPage: 50, docsData: [],\n"
    "  docsTotal: 0, sortKey: null, sortDir: 1, collections: [],\n"
    "  health: null, viewMode: 'list', queryViewMode: 'list', lastQueryResult: null,\n"
    "};\n"
    "\n"
    "function $(id) { return document.getElementById(id); }\n"
    "function escapeHtml(s) { return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;'); }\n"
    "function escapeAttr(s) { return String(s).replace(/\\\\/g,'\\\\\\\\').replace(/'/g,\"\\\\'\"); }\n"
    "\n"
    "async function apiHealth() { return (await fetch('/health')).json(); }\n"
    "async function apiListColls() { return (await fetch('/collections')).json(); }\n"
    "async function apiQuery(sql) { return (await fetch('/query',{method:'POST',headers:{'Content-Type':'text/plain'},body:sql})).json(); }\n"
    "async function apiImport(c,t) { return (await fetch('/import?coll='+encodeURIComponent(c),{method:'POST',body:t})).json(); }\n"
    "async function apiBatch(b) { return (await fetch('/batch',{method:'POST',headers:{'Content-Type':'text/plain'},body:b})).json(); }\n"
    "\n"
    "// ==== Status ====\n"
    "async function refreshStatus() {\n"
    "  try {\n"
    "    const h=await apiHealth(); S.health=h;\n"
    "    $('status-dot').className='dot ok';\n"
    "    $('status-text').textContent=h.collections+' coll \xc2\xb7 WAL '+(h.wal_enabled?'on':'off');\n"
    "    $('db-badge').textContent=h.db;\n"
    "  } catch(e) {\n"
    "    $('status-dot').className='dot err';\n"
    "    $('status-text').textContent='disconnected';\n"
    "  }\n"
    "}\n"
    "\n"
    "// ==== Sidebar tree (like Compass) ====\n"
    "async function refreshSidebar() {\n"
    "  try {\n"
    "    const j=await apiListColls();\n"
    "    S.collections=j.collections||[];\n"
    "  } catch(e) {}\n"
    "  renderSidebar();\n"
    "}\n"
    "\n"
    "function renderSidebar() {\n"
    "  const tree=$('sidebar-tree');\n"
    "  const db=S.health?S.health.db:'hugo';\n"
    "  let html='<div class=\"side-tree-parent\"><span class=\"arrow\">\xe2\x96\xbc</span>\xf0\x9f\x97\x84\xef\xb8\x8f '+escapeHtml(db)+'</div>';\n"
    "  if(S.collections.length===0) {\n"
    "    html+='<div class=\"side-empty\">No collections<br><span style=\"font-size:10px\">Use Import tab to add data</span></div>';\n"
    "  } else {\n"
    "    html+=S.collections.map(c=>\n"
    "      '<div class=\"coll-item'+(S.currentColl===c.name?' active':'')+'\" onclick=\"selectCollection(\\''+escapeAttr(c.name)+'\\')\">'+\n"
    "        '<span class=\"icon\">\xf0\x9f\x93\x8b</span>'+\n"
    "        '<span class=\"name\">'+escapeHtml(c.name)+'</span>'+\n"
    "        '<span class=\"cnt\">'+c.count+'</span>'+\n"
    "        '<span class=\"dots\">\xe2\x8b\xaf</span>'+\n"
    "      '</div>').join('');\n"
    "  }\n"
    "  tree.innerHTML=html;\n"
    "}\n"
    "\n"
    "function selectCollection(name) {\n"
    "  S.currentColl=name; S.docsPage=0; S.sortKey=null;\n"
    "  renderSidebar();\n"
    "  switchTab('docs');\n"
    "}\n"
    "\n"
    "// ==== Tabs + Breadcrumb ====\n"
    "function switchTab(name) {\n"
    "  document.querySelectorAll('.pane').forEach(p=>p.classList.toggle('active',p.dataset.pane===name));\n"
    "  renderBreadcrumb(name);\n"
    "  renderTabBar(name);\n"
    "  if(name==='overview') renderOverview();\n"
    "  if(name==='docs') docsReload();\n"
    "  if(name==='import'&&S.currentColl) $('import-coll').value=S.currentColl;\n"
    "}\n"
    "\n"
    "function renderBreadcrumb(tab) {\n"
    "  const db=S.health?S.health.db:'hugo';\n"
    "  let html='<a onclick=\"switchTab(\\'overview\\')\">'+escapeHtml(db)+'</a>';\n"
    "  if(S.currentColl) {\n"
    "    html+='<span class=\"sep\">\xe2\x80\xba</span><a onclick=\"selectCollection(\\''+escapeAttr(S.currentColl)+'\\')\">'+escapeHtml(S.currentColl)+'</a>';\n"
    "  }\n"
    "  if(tab&&tab!=='overview'&&tab!=='docs') {\n"
    "    const names={query:'Query',batch:'Batch',import:'Import'};\n"
    "    html+='<span class=\"sep\">\xe2\x80\xba</span><span class=\"current\">'+(names[tab]||tab)+'</span>';\n"
    "  }\n"
    "  $('breadcrumb').innerHTML=html;\n"
    "}\n"
    "\n"
    "function renderTabBar(activeTab) {\n"
    "  const tabs=[\n"
    "    {id:'overview',label:'Overview'},\n"
    "    {id:'docs',label:'Documents',badge:S.currentColl?(S.collections.find(c=>c.name===S.currentColl)||{}).count||'':null},\n"
    "    {id:'query',label:'Query'},\n"
    "    {id:'batch',label:'Batch'},\n"
    "    {id:'import',label:'Import'},\n"
    "  ];\n"
    "  $('tab-bar').innerHTML=tabs.map(t=>\n"
    "    '<div class=\"tab-item'+(activeTab===t.id?' active':'')+'\" data-tab=\"'+t.id+'\" onclick=\"switchTab(\\''+t.id+'\\')\">'+\n"
    "    t.label+\n"
    "    (t.badge!=null?'<span class=\"badge\">'+t.badge+'</span>':'')+\n"
    "    '</div>').join('');\n"
    "}\n"
    "\n"
    "// ==== Overview ====\n"
    "function renderOverview() {\n"
    "  const h=S.health||{};\n"
    "  const colls=S.collections;\n"
    "  const total=colls.reduce((s,c)=>s+c.count,0);\n"
    "  $('overview-stats').innerHTML=\n"
    "    '<div class=\"stat-card\"><div class=\"label\">Database</div><div class=\"value\" style=\"font-size:18px\">'+escapeHtml(h.db||'\xe2\x80\x94')+'</div></div>'+\n"
    "    '<div class=\"stat-card\"><div class=\"label\">Collections</div><div class=\"value\">'+colls.length+'</div></div>'+\n"
    "    '<div class=\"stat-card\"><div class=\"label\">Total Documents</div><div class=\"value\">'+total+'</div></div>'+\n"
    "    '<div class=\"stat-card\"><div class=\"label\">WAL</div><div class=\"value\" style=\"color:'+(h.wal_enabled?'var(--green-darker)':'var(--text-muted)')+'\">'+\n"
    "    (h.wal_enabled?'ON':'OFF')+'</div><div class=\"sub\">Write-ahead logging</div></div>';\n"
    "  if(colls.length===0) {\n"
    "    $('overview-colls').innerHTML='<div class=\"empty\">No collections yet. Use the Import tab to add data.</div>';\n"
    "    return;\n"
    "  }\n"
    "  $('overview-colls').innerHTML='<table><thead><tr><th>Name</th><th style=\"text-align:right\">Documents</th><th style=\"text-align:right\">Next ID</th><th></th></tr></thead><tbody>'+\n"
    "    colls.map(c=>'<tr><td><a style=\"color:var(--blue);cursor:pointer\" onclick=\"selectCollection(\\''+escapeAttr(c.name)+'\\')\">'+escapeHtml(c.name)+'</a></td><td class=\"num\">'+c.count+'</td><td class=\"num\">'+c.next_id+'</td><td><button class=\"btn btn-outline btn-sm\" onclick=\"selectCollection(\\''+escapeAttr(c.name)+'\\')\">View \xe2\x86\x92</button></td></tr>').join('')+\n"
    "    '</tbody></table>';\n"
    "}\n"
    "\n"
    "// ==== Documents ====\n"
    "function setViewMode(mode) {\n"
    "  S.viewMode=mode;\n"
    "  $('view-list').className=mode==='list'?'active':'';\n"
    "  $('view-table').className=mode==='table'?'active':'';\n"
    "  renderDocsContent();\n"
    "}\n"
    "\n"
    "async function docsReload() {\n"
    "  if(!S.currentColl) { $('docs-empty').style.display='block'; $('docs-view').style.display='none'; return; }\n"
    "  $('docs-empty').style.display='none'; $('docs-view').style.display='block';\n"
    "  S.docsPerPage=parseInt($('docs-per-page').value);\n"
    "  const skip=S.docsPage*S.docsPerPage;\n"
    "  let sql='funden '+S.currentColl+' lime '+S.docsPerPage+' skopan '+skip;\n"
    "  const filter=$('docs-filter').value.trim();\n"
    "  if(filter) sql='funden '+S.currentColl+' haar '+filter+' lime '+S.docsPerPage+' skopan '+skip;\n"
    "  const r=await apiQuery(sql);\n"
    "  if(!r.ok) {\n"
    "    $('docs-table').innerHTML='<div class=\"result-banner err\">err '+escapeHtml(r.err_code)+': '+escapeHtml(r.err_msg)+'</div>';\n"
    "    return;\n"
    "  }\n"
    "  S.docsData=r.docs||[];\n"
    "  const coll=S.collections.find(c=>c.name===S.currentColl);\n"
    "  S.docsTotal=coll?coll.count:S.docsData.length;\n"
    "  renderDocsContent(); updatePager(); renderTabBar('docs');\n"
    "}\n"
    "\n"
    "function docsApplyFilter() { S.docsPage=0; docsReload(); }\n"
    "\n"
    "function renderDocsContent() {\n"
    "  if(S.viewMode==='list') renderDocsCards(); else renderDocsTable();\n"
    "}\n"
    "\n"
    "function renderDocsCards() {\n"
    "  let docs=sortDocs(S.docsData);\n"
    "  if(docs.length===0) { $('docs-table').innerHTML='<div class=\"empty\">No documents found</div>'; return; }\n"
    "  $('docs-table').innerHTML=docs.map(d=>{\n"
    "    let html='<div class=\"doc-card\">';\n"
    "    for(const k of Object.keys(d)) {\n"
    "      html+='<div class=\"doc-field\"><span class=\"doc-key\">'+escapeHtml(k)+'</span>'+renderDocValue(d[k],k)+'</div>';\n"
    "    }\n"
    "    html+='</div>';\n"
    "    return html;\n"
    "  }).join('');\n"
    "}\n"
    "\n"
    "function renderDocValue(v,key) {\n"
    "  if(v===null||v===undefined) return '<span class=\"doc-val-null\">null</span>';\n"
    "  if(typeof v==='number') {\n"
    "    if(key==='id') return '<span class=\"doc-val-id\">'+v+'</span>';\n"
    "    return '<span class=\"doc-val-num\">'+v+'</span>';\n"
    "  }\n"
    "  if(typeof v==='boolean') return '<span class=\"doc-val-bool\">'+v+'</span>';\n"
    "  if(typeof v==='string') {\n"
    "    if(/^\\d{4}-\\d{2}-\\d{2}T/.test(v)) return '<span class=\"doc-val-date\">'+escapeHtml(v)+'</span>';\n"
    "    return '<span class=\"doc-val-str\">'+escapeHtml(v)+'</span>';\n"
    "  }\n"
    "  return '<span class=\"doc-val-obj\">Object</span>';\n"
    "}\n"
    "\n"
    "function renderDocsTable() {\n"
    "  let docs=sortDocs(S.docsData);\n"
    "  if(docs.length===0) { $('docs-table').innerHTML='<div class=\"empty\">No documents found</div>'; return; }\n"
    "  const keys=[]; const seen=new Set();\n"
    "  for(const d of docs) for(const k of Object.keys(d)) if(!seen.has(k)){seen.add(k);keys.push(k);}\n"
    "  keys.sort((a,b)=>a==='id'?-1:b==='id'?1:0);\n"
    "  let html='<div class=\"table-scroll-container\"><table><thead><tr>';\n"
    "  for(const k of keys) {\n"
    "    let cls='',arrow='<span class=\"sort-arrow\">\xe2\x87\x85</span>';\n"
    "    if(S.sortKey===k) { arrow=S.sortDir===1?'<span class=\"sort-arrow\">\xe2\x96\xb2</span>':'<span class=\"sort-arrow\">\xe2\x96\xbc</span>'; }\n"
    "    html+='<th class=\"'+cls+'\" onclick=\"toggleSort(\\''+escapeAttr(k)+'\\')\">'+escapeHtml(k)+arrow+'</th>';\n"
    "  }\n"
    "  html+='</tr></thead><tbody>';\n"
    "  for(const d of docs) {\n"
    "    html+='<tr>';\n"
    "    for(const k of keys) html+=renderTdCell(d[k],k==='id');\n"
    "    html+='</tr>';\n"
    "  }\n"
    "  html+='</tbody></table></div>';\n"
    "  $('docs-table').innerHTML=html;\n"
    "}\n"
    "\n"
    "function sortDocs(docs) {\n"
    "  if(!S.sortKey) return docs;\n"
    "  return [...docs].sort((a,b)=>{\n"
    "    const av=a[S.sortKey], bv=b[S.sortKey];\n"
    "    const aNull = (av === null || av === undefined);\n"
    "    const bNull = (bv === null || bv === undefined);\n"
    "    /* Null/undefined lu\xc3\xb4n xu\xe1\xbb\x91ng cu\xe1\xbb\x91i c\xc3\xb9ng b\xe1\xba\xa5t k\xe1\xbb\x83 sort direction */\n"
    "    if(aNull && bNull) return 0;\n"
    "    if(aNull) return 1;   /* a null \xe2\x86\x92 a xu\xe1\xbb\x91ng d\xc6\xb0\xe1\xbb\x9bi */\n"
    "    if(bNull) return -1;  /* b null \xe2\x86\x92 b xu\xe1\xbb\x91ng d\xc6\xb0\xe1\xbb\x9bi */\n"
    "    /* Sort non-null values b\xc3\xacnh th\xc6\xb0\xe1\xbb\x9dng */\n"
    "    if(av < bv) return -S.sortDir;\n"
    "    if(av > bv) return S.sortDir;\n"
    "    return 0;\n"
    "  });\n"
    "}\n"
    "\n"
    "function toggleSort(key) {\n"
    "  if(S.sortKey===key) S.sortDir*=-1;\n"
    "  else { S.sortKey=key; S.sortDir=1; }\n"
    "  renderDocsContent();\n"
    "}\n"
    "\n"
    "function renderTdCell(v,isId) {\n"
    "  if(v===null||v===undefined) return '<td class=\"null\">null</td>';\n"
    "  if(typeof v==='number') return '<td class=\"num'+(isId?' id-col':'')+'\">'+v+'</td>';\n"
    "  if(typeof v==='boolean') return '<td class=\"bool\">'+v+'</td>';\n"
    "  if(typeof v==='string') return '<td class=\"str\">'+escapeHtml(v)+'</td>';\n"
    "  return '<td>'+escapeHtml(JSON.stringify(v))+'</td>';\n"
    "}\n"
    "\n"
    "function updatePager() {\n"
    "  const start=S.docsPage*S.docsPerPage+1;\n"
    "  const end=Math.min(start+S.docsPerPage-1,S.docsTotal);\n"
    "  const tp=Math.max(1,Math.ceil(S.docsTotal/S.docsPerPage));\n"
    "  $('docs-page-info').textContent=start+' \xe2\x80\x93 '+end+' of '+S.docsTotal;\n"
    "  $('docs-count-info').textContent='Showing '+S.docsData.length+' documents from \"'+S.currentColl+'\"';\n"
    "  $('docs-prev').disabled=S.docsPage===0;\n"
    "  $('docs-next').disabled=(S.docsPage+1)*S.docsPerPage>=S.docsTotal;\n"
    "}\n"
    "\n"
    "function docsPage(d) { S.docsPage=Math.max(0,S.docsPage+d); docsReload(); }\n"
    "\n"
    "// ==== Query ====\n"
    "function setQueryViewMode(mode) {\n"
    "  S.queryViewMode = mode;\n"
    "  $('qview-list').className = mode==='list' ? 'active' : '';\n"
    "  $('qview-table').className = mode==='table' ? 'active' : '';\n"
    "  if (S.lastQueryResult) $('query-result').innerHTML = renderQueryResult(S.lastQueryResult);\n"
    "}\n"
    "\n"
    "async function runQuery() {\n"
    "  const q=$('query').value.trim(); if(!q) return;\n"
    "  $('query-result').innerHTML='<div class=\"result-banner info\">executing...</div>';\n"
    "  try {\n"
    "    const r=await apiQuery(q);\n"
    "    S.lastQueryResult = r;\n"
    "    $('query-result').innerHTML=renderQueryResult(r);\n"
    "    refreshStatus(); refreshSidebar();\n"
    "  } catch(e) {\n"
    "    S.lastQueryResult = null;\n"
    "    $('query-result').innerHTML='<div class=\"result-banner err\">Network error: '+escapeHtml(e.message)+'</div>';\n"
    "  }\n"
    "}\n"
    "\n"
    "function renderQueryResult(r) {\n"
    "  if(!r.ok) return '<div class=\"result-banner err\">err '+escapeHtml(r.err_code||'?')+' \xe2\x80\x94 '+escapeHtml(r.err_msg||'')+'</div>';\n"
    "  let html='<div class=\"result-banner ok\">\xe2\x9c\x93 '+r.count+' document'+(r.count===1?'':'s')+(r.info?' \xc2\xb7 '+escapeHtml(r.info):'')+'</div>';\n"
    "  if(r.docs&&r.docs.length>0) {\n"
    "    if (S.queryViewMode === 'table') {\n"
    "      html += renderQueryResultTable(r.docs);\n"
    "    } else {\n"
    "      html+=r.docs.map(d=>{\n"
    "        let h='<div class=\"doc-card\">';\n"
    "        for(const k of Object.keys(d)) h+='<div class=\"doc-field\"><span class=\"doc-key\">'+escapeHtml(k)+'</span>'+renderDocValue(d[k],k)+'</div>';\n"
    "        return h+'</div>';\n"
    "      }).join('');\n"
    "    }\n"
    "  }\n"
    "  return html;\n"
    "}\n"
    "\n"
    "function renderQueryResultTable(docs) {\n"
    "  const keys=[]; const seen=new Set();\n"
    "  for(const d of docs) for(const k of Object.keys(d)) if(!seen.has(k)){seen.add(k);keys.push(k);}\n"
    "  keys.sort((a,b)=>a==='id'?-1:b==='id'?1:0);\n"
    "  let html='<div class=\"table-scroll-container\"><table><thead><tr>';\n"
    "  for(const k of keys) html+='<th style=\"cursor:default\">'+escapeHtml(k)+'</th>';\n"
    "  html+='</tr></thead><tbody>';\n"
    "  for(const d of docs) {\n"
    "    html+='<tr>';\n"
    "    for(const k of keys) html+=renderTdCell(d[k],k==='id');\n"
    "    html+='</tr>';\n"
    "  }\n"
    "  html+='</tbody></table></div>';\n"
    "  return html;\n"
    "}\n"
    "\n"
    "function setQuery(q) { $('query').value=q; switchTab('query'); $('query').focus(); }\n"
    "\n"
    "// ==== Batch ====\n"
    "async function runBatch() {\n"
    "  const b=$('batch-text').value; if(!b.trim()) return;\n"
    "  $('batch-result').innerHTML='<div class=\"result-banner info\">running batch...</div>';\n"
    "  try {\n"
    "    const r=await apiBatch(b);\n"
    "    $('batch-result').innerHTML=renderBatchResult(r);\n"
    "    refreshStatus(); refreshSidebar();\n"
    "  } catch(e) {\n"
    "    $('batch-result').innerHTML='<div class=\"result-banner err\">Network error</div>';\n"
    "  }\n"
    "}\n"
    "\n"
    "function renderBatchResult(r) {\n"
    "  let html='<div class=\"result-banner ok\">'+r.ok_count+'/'+r.total+' ok \xc2\xb7 '+r.err_count+' err \xc2\xb7 '+r.total_sec.toFixed(3)+'s total</div>';\n"
    "  html+='<div class=\"batch-stats\">'+\n"
    "    '<div class=\"batch-stat\"><div class=\"k\">Total</div><div class=\"v\">'+r.total+'</div></div>'+\n"
    "    '<div class=\"batch-stat\"><div class=\"k\">Avg ms</div><div class=\"v\">'+r.avg_ms.toFixed(3)+'</div></div>'+\n"
    "    '<div class=\"batch-stat\"><div class=\"k\">Min ms</div><div class=\"v\">'+r.min_ms.toFixed(3)+'</div></div>'+\n"
    "    '<div class=\"batch-stat\"><div class=\"k\">Max ms</div><div class=\"v\">'+r.max_ms.toFixed(3)+'</div></div>'+\n"
    "    '<div class=\"batch-stat\"><div class=\"k\">p50 ms</div><div class=\"v\">'+r.p50_ms.toFixed(3)+'</div></div>'+\n"
    "    '<div class=\"batch-stat\"><div class=\"k\">p95 ms</div><div class=\"v\">'+r.p95_ms.toFixed(3)+'</div></div>'+\n"
    "    '<div class=\"batch-stat\"><div class=\"k\">p99 ms</div><div class=\"v\">'+r.p99_ms.toFixed(3)+'</div></div>'+\n"
    "  '</div>';\n"
    "  if(r.results&&r.results.length>0) {\n"
    "    html+='<table><thead><tr><th>#</th><th>Query</th><th style=\"text-align:right\">Time (ms)</th><th>Result</th></tr></thead><tbody>';\n"
    "    r.results.forEach((item,i)=>{\n"
    "      const ok=item.result&&item.result.ok;\n"
    "      const info=ok?'<span style=\"color:var(--green-darker)\">\xe2\x9c\x93 '+item.result.count+' doc'+(item.result.count===1?'':'s')+(item.result.info?' \xc2\xb7 '+escapeHtml(item.result.info):'')+'</span>':'<span style=\"color:var(--red)\">\xe2\x9c\x97 '+escapeHtml(item.result.err_code||'?')+'</span>';\n"
    "      html+='<tr><td class=\"num\">'+(i+1)+'</td><td style=\"font-family:var(--mono);font-size:12px\">'+escapeHtml(item.query)+'</td><td class=\"num\">'+item.ms.toFixed(3)+'</td><td>'+info+'</td></tr>';\n"
    "    });\n"
    "    html+='</tbody></table>';\n"
    "  }\n"
    "  return html;\n"
    "}\n"
    "\n"
    "function loadBatchSample() {\n"
    "  $('batch-text').value='-- Sample batch\\nmadeco demo\\nvietinfo demo { name: \"Alice\", age: 25 }\\nvietinfo demo { name: \"Bob\", age: 30 }\\nvietinfo demo { name: \"Carol\", age: 28 }\\nfunden demo\\nfunden demo haar age $bh 26\\nfunden demo orange bi age desc lime 2\\nskill demo';\n"
    "}\n"
    "\n"
    "// ==== Import ====\n"
    "async function doImport(coll,text) {\n"
    "  $('import-result').innerHTML='<div class=\"result-banner info\">Uploading '+text.length+' bytes...</div>';\n"
    "  try {\n"
    "    const r=await apiImport(coll,text);\n"
    "    if(!r.ok) { $('import-result').innerHTML='<div class=\"result-banner err\">'+r.err_code+': '+r.err_msg+'</div>'; return; }\n"
    "    $('import-result').innerHTML=\n"
    "      '<div class=\"result-banner ok\">\xe2\x9c\x93 Imported '+r.docs_inserted+' / '+r.lines_read+' lines into \"'+escapeHtml(r.coll)+'\"</div>'+\n"
    "      '<div class=\"batch-stats\">'+\n"
    "        '<div class=\"batch-stat\"><div class=\"k\">Lines</div><div class=\"v\">'+r.lines_read+'</div></div>'+\n"
    "        '<div class=\"batch-stat\"><div class=\"k\">Inserted</div><div class=\"v\" style=\"color:var(--green-darker)\">'+r.docs_inserted+'</div></div>'+\n"
    "        '<div class=\"batch-stat\"><div class=\"k\">Parse err</div><div class=\"v\" style=\"color:'+(r.parse_errors?'var(--red)':'var(--text-muted)')+'\">'+r.parse_errors+'</div></div>'+\n"
    "        '<div class=\"batch-stat\"><div class=\"k\">Elapsed</div><div class=\"v\">'+r.elapsed_sec.toFixed(3)+'s</div></div>'+\n"
    "        '<div class=\"batch-stat\"><div class=\"k\">Rate</div><div class=\"v\">'+(r.elapsed_sec>0?Math.round(r.docs_inserted/r.elapsed_sec):'\xe2\x80\x94')+' doc/s</div></div>'+\n"
    "      '</div>';\n"
    "    refreshAll();\n"
    "  } catch(e) { $('import-result').innerHTML='<div class=\"result-banner err\">Network error</div>'; }\n"
    "}\n"
    "\n"
    "function handleDrop(ev) {\n"
    "  ev.preventDefault(); $('dropzone').classList.remove('drag');\n"
    "  const f=ev.dataTransfer.files[0]; if(f) readAndImport(f);\n"
    "}\n"
    "function handleFileInput(ev) { const f=ev.target.files[0]; if(f) readAndImport(f); }\n"
    "function readAndImport(f) {\n"
    "  const c=$('import-coll').value.trim();\n"
    "  if(!c) { $('import-result').innerHTML='<div class=\"result-banner err\">Please enter collection name first</div>'; return; }\n"
    "  const r=new FileReader(); r.onload=()=>doImport(c,r.result); r.readAsText(f);\n"
    "}\n"
    "function importPasted() {\n"
    "  const c=$('import-coll').value.trim(), t=$('import-text').value;\n"
    "  if(!c) { $('import-result').innerHTML='<div class=\"result-banner err\">Please enter collection name first</div>'; return; }\n"
    "  if(!t.trim()) return;\n"
    "  doImport(c,t);\n"
    "}\n"
    "\n"
    "// ==== Init ====\n"
    "async function refreshAll() { await refreshStatus(); await refreshSidebar(); }\n"
    "$('query').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();runQuery();}});\n"
    "$('batch-text').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();runBatch();}});\n"
    "(async()=>{\n"
    "  await refreshAll();\n"
    "  switchTab('overview');\n"
    "  setInterval(refreshStatus,15000);\n"
    "})();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "";

#endif
